### ISSUE TITLE
Can't drag the range handles

### ISSUE THREAD

**Issue by cameroncooke** [chicio/RangeUISlider#1]
I've used the library as a Cocoapod in a project and found that it's very very difficult to actually grab the range handles. It takes many attempts.

I've also tried your demo project and it suffers the same problem. While it seems highly customisable it doesn't actually work.

I'm running on iOS 10.3.1.

**Comment by chicio** [comment]
Hi @cameroncooke, I improved a lot the drag of the knob. Now they work as you expect. I release also a new version on cocoapods (1.0.2). 
I hope you will continue to use the library. If you like my work, support me by adding my repo to your favourites. I consider the issue closed, but let me know if there are other problems. I'm at your disposal :).
