### ISSUE TITLE
can't get the selected values

### ISSUE THREAD

**Issue by danielghre** [chicio/RangeUISlider#10]
hi, 

can someone help me to access values from the slider while the user is changing it ? I just need to print those values. 

this is what I have done but nothing is happening

```
@IBOutlet weak var ageSlider: RangeUISlider!
  
@objc func rangeIsChanging(minValueSelected: CGFloat, maxValueSelected: CGFloat, slider: RangeUISlider){
    }
```

Thank you

**Comment by chicio** [comment]
Hi @danielghre,
did you set the `delegate` property of your `ageSlider`?
You have to do something similar to what I do in my demo project (have a look here https://github.com/chicio/RangeUISlider/blob/master/Demo/ViewController.swift). Add something like this in the `viewDidLoad` of your controller (the controller must implement the `RangeUISliderDelegate` protocol). 

```
    override func viewDidLoad() {
        super.viewDidLoad()
        ageSlider.delegate = self
    }
```

Let me know if everything work as expected (and add a star to this repo if you like the project).
Thanks,
Fabrizio.
