### ISSUE TITLE
Step value

### ISSUE THREAD

**Issue by jonathansolorzn** [chicio/RangeUISlider#13]
When working when ranges there are use cases when it's necessary to step by 0.5 or 5... etc, possibilities are infinite, I couldn't find a property to define the step value.

It would be nice to have an ibdesignable property called step of type double so that it's open for any value.

**Comment by chicio** [comment]
Hi @fenixsolorzano,
thank you for your suggestion. If I have time I will try to work on this feature in the next weeks (or if you can you can submit a PR).

**PS remember to support my work by starring my repo** ⭐️ 

Best regards,
Fabrizio.

**Comment by chicio** [comment]
Hi @fenixsolorzano ,
I opened a new pull request #15 with the implementation of the new step increment feature that you requested. Can you tested it out? (In any case I will merge the new stuff during next week).
You can try the new stuff also in the Demo project of RangeUISlider (the second slider of the first tab is a step increment slider).

⭐️⭐️ **Remember to support my work by starring my repo** ⭐️⭐️ 

Thank you,
Fabrizio.

**Comment by jonathansolorzn** [comment]
Cool!!

I ended up using `isChanging` and `changeFinished` delegates to my needs, but I'll try out the new step feature you added as soon as possible✌️

**Comment by chicio** [comment]
Hi @fenixsolorzano,
I'm going to close the issue, because I merged PR #15 into master and released it to cocoapods.

⭐️⭐️ **Remember to support my work by starring my repo** ⭐️⭐️

Thank you,
Fabrizio.

**Comment by jonathansolorzn** [comment]
Thanks @chicio!
