### ISSUE TITLE
Refresh View On Programmatic Value Change

### ISSUE THREAD

**Issue by iUsmanN** [chicio/RangeUISlider#16]
I can't seem to find a solution regarding updating the view using code. If I set the default Left Knob value in the code after it has been loaded, is there any way to refresh the view so that the value can be updated in the slider ?

Kindly look into this :)
Thanks !

Usman.

**Comment by punitsilversky** [comment]
Hi @chicio I've Same Issue, I'm unable to set default value for slider Programmatically.

Pls Look into this....

**Comment by chicio** [comment]
Hi @iUsmanN and @punitsilversky ,

sorry for the delayed answer. I implemented the requested feature in a new pull request.

#18 Programmatic knobs values change

Can you try to pull the branch of these pull request and test the new feature? You can find a usage example in the `ChangeProgrammaticViewController` https://github.com/chicio/RangeUISlider/pull/18/files#diff-e3dcff799e3f78bab4e7980e510f286d. Just a note:

- use `defaultValueLeftKnob` and `defaultValueRightKnob` to set the initial value of the knobs (so when the slider view will be loaded)
- use `changeLeftKnob(value:)` and `changeRightKnob(value:)` to set a new value for the knobs programmatically when the slider view is already on screen

I will merge the PR in the next days, any feedback will be appreciated.

PS. remember to ⭐️ start ⭐️ this repo to support my work. Thank you!!!

**Comment by punitsilversky** [comment]
Thanks @chicio,

I've checked your branch code and it is working.

I think you need to merge this branch to master.

If any one need it, they can try it

**Comment by chicio** [comment]
@punitsilversky @iUsmanN version 1.12.0 released to cocoapods and SwiftPM. Thank you.
