### ISSUE TITLE
Unable to Refresh View On Programmatic Value Change

### ISSUE THREAD

**Issue by punitsilversky** [chicio/RangeUISlider#19]
Hi @chicio I can't update scaleMaxValue programmatically after it has been loaded, is there any way to refresh the view so that the value can be updated in the slider ?
I'm updating scaleMaxValue in my web service success and also I tested that the value was updated, But view is not updating accordingly.

Pls Look into this....

Thanks!

**Comment by chicio** [comment]
Hi @punitsilversky ,

I opened a new pull request with the implementation of the feature you requested. You can now change the scaleMinValue and scaleMaxValue programmatically (you can find an example in the demo folder in the `ChangeScaleProgrammaticViewController`). Can you test the RangeUISlider version using the branch of the pull request linked to this issue (#20)? If you confirm that everything works fine I will soon merge the PR and release a new version of RangeUISlider.

Thank you,
Fabrizio.

**Comment by punitsilversky** [comment]
Hi @chicio,

I've checked your branch code and it is working.
Thanks for your effort, I appreciated that

Thank you,
Punit.

**Comment by chicio** [comment]
Thank you for your feedback @punitsilversky . I will release a new version of RangeUISlider with the new feature in the following days.

**Comment by chicio** [comment]
Hi @punitsilversky , version 1.12.1 released on Cocoapods (and tag also available for SwiftPM). Than you again for your feedback.
