### ISSUE TITLE
Default knob value?

### ISSUE THREAD

**Issue by MachiAngel** [chicio/RangeUISlider#2]
Can i set default value for knob?  thanks you answer first !!

**Comment by chicio** [comment]
Hi @MachiAngel, at the moment is not possible to add a default value. I will add this functionality in the next days and let you know when it will be available.

**Comment by chicio** [comment]
Hi @MachiAngel, I added the possibility to set a default starting value for the left and right knob. You can find them in version 1.1.0 (already pushed on Cocoapods).
Let me know if it works. 
Please support my work by starring my repositories (including this one :) ).

**Comment by MachiAngel** [comment]
i see , thx ur reply , great job also !!


________________________________
寄件者: Fabrizio Duroni <notifications@github.com>
寄件日期: 2017年5月31日 下午 03:50
收件者: chicio/RangeUISlider
副本: ShiangYu Huang; Mention
主旨: Re: [chicio/RangeUISlider] Default knob value? (#2)


Hi @MachiAngel<https://github.com/machiangel>, at the moment is not possible to add a default value. I will add this functionality in the next days and let you know when it will be available.

**Comment by chicio** [comment]
Thank you for your answer @MachiAngel. Remember to support my work by starring my repo :)
