### ISSUE TITLE
Support RTL in seeking Slider

### ISSUE THREAD

**Issue by MoElnaggar14** [chicio/RangeUISlider#21]
**Describe the bug**
seeking is scrolling in the opposite direction in RTL.

**To Reproduce**
1. Using RangUISlider in App Support RTL.

**Expected behaviour**
seeking should work from RTL for min and LTR for max.

**Comment by chicio** [comment]
Hi @MoElnaggar14 , thank you for your feedback. I will work on this in the following days. I will let you know when a pull request is ready

In the meantime you can support my work by ⭐️ starring ⭐️ the repository. 

Thanks,
Fabrizio.

**Comment by chicio** [comment]
Hi @MoElnaggar14 ,

I'm here again to tell you that I implemented the feature you asked in this issue (it was quicker than I was expecting 😅). Can you test the code contained in the pull request below and try the new stuff to see if it works as you expect? 

[Add support for RTL (Closes #21) #22](https://github.com/chicio/RangeUISlider/pull/22)

After your confirmation, I will release a new version of RangeUISlider. 

Thanks,
Fabrizio.

**Comment by MoElnaggar14** [comment]
Hello @chicio, 
Thank you for the quick implementation for this feature. 

cool, I'll test it today and back to you in #22 

Thanks

**Comment by MoElnaggar14** [comment]
https://user-images.githubusercontent.com/21294763/103179113-4f21b900-4891-11eb-8af0-cb0e45aad49a.mov

I just tested the #22. Unfortunately, it's the same results

**Comment by chicio** [comment]
Hi @MoElnaggar14 , sorry to hear that 😔. I think I misunderstood the problem. I will work on it today and I will let you know when I have something ready.

**Comment by chicio** [comment]
Hi @MoElnaggar14 , I made the fix. If you test again the code in the pull request I sent you before you should get the expected behaviour. Attached here you can find also a video that show the demo project running in simulated RTL mode where RangeUISlider works as expected. 

https://user-images.githubusercontent.com/4048413/103205778-a60fa880-48fa-11eb-94a6-a6081ad1bffc.mov

**Comment by MoElnaggar14** [comment]
Hi @chicio 
I'll test it today. I really appreciate your quick response.

Thank,
Mohammed

**Comment by chicio** [comment]
Hi @MoElnaggar14 and happy new year 🎊!! Did you have the time to try out the PR code with the new implementation? 

Thanks, 
Fabrizio.

**Comment by MoElnaggar14** [comment]
Happy new year @chicio , wishing you the best.

Absolutely, i'll do it today and keep you updated 🙏🏻

**Comment by chicio** [comment]
@MoElnaggar14 Any news?

**Comment by MoElnaggar14** [comment]
Testing, just a sec

**Comment by MoElnaggar14** [comment]
Hi @chicio , sorry for the late test. 

Awesome 👏looks good and works fine.

**Comment by chicio** [comment]
Thank you @MoElnaggar14 🙏. I will prepare a new release in the afternoon 🚀🚀
