### ISSUE TITLE
Moving labels under knobs

### ISSUE THREAD

**Issue by MichaelGrigoryan** [chicio/RangeUISlider#38]
Hello RangeUISlider team.
I think it would be great for developers if you will add moving labels under left and right knobs, like it is demonstrated in the link above. There is labels above, but it would be amazing that you can add both above/under functionalities. Thank you.
https://raw.githubusercontent.com/WorldDownTown/RangeSeekSlider/master/images/demo.gif

**Comment by chicio** [comment]
Hi @MichaelGrigoryan ,

Here I am (the only member of RangeUISlider team 😅). I will try to plan the development of this feature for the next months (at the moment I finished a big rewrite of this library and I have another open source project to follow). So you need the wait a little bit. In the meantime if you still need this feature and you would like to help me you can try to implement it by submitting a MR.

Thanks,
Fabrizio.

PS remember to support my work by ⭐️ starring ⭐️ my repository

**Comment by MichaelGrigoryan** [comment]
@chicio Thank you for your answer. 👍 I appreciate your work, great!

**Comment by MichaelGrigoryan** [comment]
@chicio also a quick fix in my opinion would be that you will allow to get left and right knobs center positions.

**Comment by chicio** [comment]
Hi @MichaelGrigoryan , in the end I decided to work on this 😂. In the pull request below you can find the implementation of the new feature, with some example contained in the demo project. It is already full compatible with UIKit or SwiftUI.

https://github.com/chicio/RangeUISlider/pull/42

Attached a video of the working demo.

https://user-images.githubusercontent.com/4048413/109544632-176d0280-7ac8-11eb-930d-86f4c4a6271b.mov

I will merge this in the next days. I hope it can help you.

Thanks,
Fabrizio.

**Comment by chicio** [comment]
Merged. You can find it on master (and soon in a new version).

**Comment by vfumin** [comment]
Need customing label position under slider)

**Comment by chicio** [comment]
Hi @vfumin , I added the functionality. You can find it on master. I will release version 3.0.0 in the next days. You can check some example in the demo project (see screen "Only colours")
