### ISSUE TITLE
User Defined Runtime Attributes broke with macOS Sierra update 10.12.6

### ISSUE THREAD

**Issue by tappella** [chicio/RangeUISlider#4]
Hi, just FYI,

with the macOSSierra update, the user defined attributes in the editor started throwing warnings.
Thank you!

<img width="337" alt="screenshot 2017-07-20 14 47 52" src="https://user-images.githubusercontent.com/3381904/28431386-90e5838c-6d5a-11e7-9a8d-7e44384e76c2.png">

**Comment by chicio** [comment]
Hi again @tappella :),
I will try to investigate also on this problem during next  weekend.
Again, support my work by adding my reposto you favourites by starring them.

Thank you,
Fabrizio.

**Comment by tappella** [comment]
Definitely! thanks a ton for the wonderful job, Fabrizio.

**Comment by chicio** [comment]
Hi @tappella,
I investigated the issue you reported here. This is not a problem of my library. It is a known Xcode problem. You can find more information on the web, for example here:

https://stackoverflow.com/questions/26656400/uibutton-with-ib-designable-throws-runtime-attribute-warning-and-does-not-render

Suggestions:
- search if Xcode made some mess with your user defined runtime attributes (sometimes it creates duplicated entry for the same key/IBInspectable)
- manually clean and manually refresh the views in Interface Builder

I'm closing the issue (and I hope one day Apple will fix it for us).
Thank you again for your support.
Fabrizio.
