### ISSUE TITLE
how to reset slider to initial value.

### ISSUE THREAD

**Issue by kumarlav0** [chicio/RangeUISlider#41]
Click on a UIButton like Reset Button. How can I reset the Slider to initial value/default values with animation?

**Comment by chicio** [comment]
Hi @kumarlav0 ,
you can use the `changeLeftKnob` and `changeRightKnob` api to programmatically reset the slider.
Thank you.

PS if you like RangeUISlider, remember to star ⭐️ it

**Comment by kumarlav0** [comment]
I have Implemented your Method RightKnob is working fine but the LeftKnob is not updating.

**Comment by chicio** [comment]
Do you have the latest version of RangeUISlider. I fixed some bugs related to the programmatic api changes.

**Comment by kumarlav0** [comment]
My Xcode Version is :  11.7 (11E801a)
As you told me to update the pod. I just updated and Now I have a lot of error in your Extension RangeSlider
ERROR is : Argument labels '(_:)' do not match any available overloads





![Screenshot 2021-03-01 at 6 11 53 PM](https://user-images.githubusercontent.com/58595312/109498865-19c86000-7aba-11eb-96e3-03b77d458a82.png)

And I fixed these Error by Using this line of Code
public func rangeSelectedColor(_ value: Color) -> RangeSlider {
        settings.values["rangeSelectedColor"] = UIColor(cgColor: value as! CGColor)
        return self
    }

![Screenshot 2021-03-01 at 6 18 14 PM](https://user-images.githubusercontent.com/58595312/109499145-817eab00-7aba-11eb-93d9-621329614cdd.png)


But still, I am facing the same issue Left Knob is not resetting to Initial. The right knob is working Fine.

**Comment by chicio** [comment]
which iOS version are you supporting? can you share more code, in particular how you are using RangeUISlider. Because if you look at the demo folder you can find some usage example (that maybe can help you).

**Comment by kumarlav0** [comment]
My Target iOS version 13.0

**Comment by SoenkeSobott** [comment]
How can I reset the slider values in SwiftUI? I am able to update the binding values for minValueSelected/maxValueSelected correctly, but the UI does not reflect the changes and stays on the old values.

@chicio I really appreciate the functionality of this slider and find it to be extremely useful. However, I am wondering if the current behavior is normal. If it is not, I can submit a feature request. If it is normal, please let me know and I will provide more information to help find a solution.
