### ISSUE TITLE
View does not respond if wrapped in a scrollview.

### ISSUE THREAD

**Issue by Zigkurat** [chicio/RangeUISlider#50]
**Describe the bug**
RangeUISlider's handles do not respond to touches, if it's placed inside a UIScrollView.

**To Reproduce**
Create a full screen UIScrollView, place some views inside it, along with RangeUISlider, so the content is larger than the scroll view, so it has a space to scroll.

**Expected behavior**
RangeUISlider responds to touches.

**Screenshots**

**Device (please complete the following information):**
 - Model: Simulator and 
 - OS: iOS 15

**Comment by Zigkurat** [comment]
Okay, I was suddenly able to fix this issue, by explicitly giving RangeUISlider a height. Seems like it was calculating it's height as 0, because I was able to reproduce this issue by giving it 0 height, and it was still visible.

You can close this issue, if there is nothing to do from your side, sorry to bother you :)

**Comment by chicio** [comment]
Hi @Zigkurat , this is a design decision in order to have the maximum flexibility during the usage of RangeUISlider. Glad you find RangeUISlider useful. Thank you.

PS support my work by starring my repository ⭐
