### ISSUE TITLE
barBorderColor crash

### ISSUE THREAD

**Issue by quyUruca** [chicio/RangeUISlider#54]
Hi!
i see "barBorderColor" has crash in Swiftui, the reason i find is UIColor from UIkit and Color from Swiftui not compatible.
Way to fix: RangeSlider+Modifiers > func barBorderColor > change parameter "UIColor" to Color. Or convert Color to UIColor
I have to stand on "pod 'RangeUISlider', '~> 3.0'". If this has fixed, please ignore this issues.

**Comment by chicio** [comment]
Hi @quyUruca , In version 4 RangeUISlider already accept `Color` as parameter. So whenever you can upgrade you will have the right version of that modifier. Thank you, Fabrizio.
