### ISSUE TITLE
Programmatically Access

### ISSUE THREAD

**Issue by rehannali** [chicio/RangeUISlider#7]
Hi, I want to know if there is support for programmatically access on properties so i can change on Run time.
Thanks

**Comment by rehannali** [comment]
There is one problem I noticed, views disturb in right to left language. In right to left language right slider should move from right to left and vice versa. It always starts from the left side.
Any suggestions to fix it.

**Comment by chicio** [comment]
Hi @rehannali ,
at the moment there's now support for programmatic access to the property or for a right to left orientation. At the moment I'm working on another project, so I will be glad to receive a pull request with the modification need to add those features 😃.
Hope to here some news from you soon.
Fabrizio.
