### ISSUE TITLE
One Knob

### ISSUE THREAD

**Issue by Ruckt** [chicio/RangeUISlider#8]
Is there a way to have just one knob?  I couldn't see one so went with another one I found, but would have preferred yours given all the other customization options.

**Comment by chicio** [comment]
Hi @Ruckt, 
no, there's no way to have just one knob. This is a "Range" slider so it will always have two knobs 😃.
Closing as this is not a real issue (it is outside the scope of the framework).
Thanks,
Fabrizio.
